### ISSUE TITLE
Not able to download client

### ISSUE THREAD

**Issue by kiddoInTheBlock** [HubSpot/BuckyClient#22]
Hello!

As my name says I am new here. I am not a dev guy.To be precise I have got a QA background for performance. I am interested in bucky and want to try it out. But I am not able to download the client. The page https://codeload.github.com/HubSpot/BuckyClient/zip/v0.2.4 loads up and show a message 'Not found'. Could you guys please guide me?

Thanks

**Comment by zackbloom** [comment]
0.2.4 is not actually a release on GitHub.  I would suggest you start with [v0.2.8](https://github.com/HubSpot/BuckyClient/archive/v0.2.8.zip).

**Comment by kiddoInTheBlock** [comment]
Thanks zackbloom. Will try v0.2.8. I guess the link on the Bucky Client web page should be rectified then.
