### ISSUE TITLE
time = process.hrtime() - throws Uncaught TypeError: process.hrtime is not a function

### ISSUE THREAD

**Issue by ishaikovsky** [HubSpot/BuckyClient#23]
Followed simple instructions configuring the BuckyClient using Browserify and it keep failing on send with the 

time = process.hrtime() - throws Uncaught TypeError: process.hrtime is not a function

message.

As I see - the browserify shim for the "process" module is really not including this method. So I assume there has to be some additional steps to get it up and running in browser?

**Comment by ishaikovsky** [comment]
added 
https://www.npmjs.com/package/browser-process-hrtime
but it didn't help.

**Comment by zackbloom** [comment]
The code you're referring to is not supposed to run on the client.  My guess is your module loader works in a way this code didn't anticipate: https://github.com/HubSpot/BuckyClient/blob/e6fe7baf8a453d31b0dff4ab8580f29cd7ae11e5/bucky.coffee#L1

**Comment by ishaikovsky** [comment]
Thanks, for the hint. I missed this condition and looked in the wrong direction. Let me try to investigate further.

**Comment by ishaikovsky** [comment]
Ok.. we needed to define window.module ourselves. 

In general it was not required by our app as everything was properly defined and required by browserify means. so we never defined any global variables. However we did it - so it will be validated properly by that check.

**Comment by CarlosHdez** [comment]
Hi, sorry to comment on an old thread, but I'm having the exact same problem, but I'm not sure how you managed to fix this @ishaikovsky. What was exactly what you exported to the global level ?
Thanks

**Comment by ishaikovsky** [comment]
By adding 

`window.module = module;`

to my plugins initialization scripts. This made it understand that I'm using browserify and register in a proper way.

**Comment by CarlosHdez** [comment]
Great, thanks.
I'm new to using browserify so I'm still new to many of this; but thank you again

**Comment by rainbow-bash** [comment]
hellow where do i add the window.module = module; idk what are the plugin initialization scripts  unu
