### ISSUE TITLE
Description of ajax requests data points

### ISSUE THREAD

**Issue by perrucci** [HubSpot/BuckyClient#29]
Hi guys,

I can't find documentation about ajax requests data points collected by BuckyClient.
From the README page:

> The data collected will look something like this for a GET request to api.hubapi.com/automation/v2/workflows:
> 
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get: "656.794|ms"
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.2xx: "1|c"
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.200: "1|c"
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.headers: "436.737|ms"
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.receiving: "0.182|ms"
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.sending: "0.059|ms"
> contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.waiting: "206.035|ms"

but what's the meaning of each of these datapoint?

Thanks
Paolo

**Comment by marlier** [comment]
Hi there --

In this example:
- The first 3 stanzas ("contacts.web.prod") are the name that you've assigned to your application.
- The next ("requests") simply designates that this is the requests portion of the data.
- The next 5 ("api.hubapi.automation.v2.workflows") are the hostname and path of the request.  In this case, the request was to https://api.hubapi[.com]/automation/v2/workflows/.  There was some reason for dropping the TLD, but at this point I can't remember what it was.
- The next ("get") is the request method. 
- The final stanza breaks down some of the various response/result options.  "2xx" is for all 200 responses (200, 204, etc).  200 is only 200 responses.  And so on.  

So "contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get" is a data point showing the time that was spent by the application contacts.web.prod, making GET requests to https://api.hubapi.com/automation/v2/workflows/.

contacts.web.prod.requests.api.hubapi.automation.v2.workflows.get.2xx is the count (thus the "|c" in the data) of GET requests to https://api.hubapi.com/automation/v2/workflows/ that returned a 2XX response code.

And so on. 

Hope that helps.

**Comment by perrucci** [comment]
Ok, thank you very much.
Therefore for each request, "get" should be egual to "headers" + "receiving" + "sending" + "waiting"?

Thanks
Paolo

**Comment by marlier** [comment]
As far as I can recall, that's correct.

**Comment by perrucci** [comment]
ok, thanks
