### ISSUE TITLE
Why not use boomerang for the client side

### ISSUE THREAD

**Issue by bluesmoon** [HubSpot/BuckyClient#4]
boomerang has been tested on thousands of websites (and over a trillion beacons so far) and has many workarounds for browser bugs that affect performance measurement.  It also has plugins to measure many other useful metrics.  Using boomerang as the front end would gain advantage of many years of work that I and other boomerang contributors have put into it.

boomerang is available under the BSD license from https://github.com/lognormal/boomerang/

**Comment by KaptaanBarbosa** [comment]
I have been trying boomerang.js , it is quite easy best part is automatic handling of sending  XHR call on soft and hard navigation ,page load and unload event etc. it automatically calculates total page load time gives you bandwidth lots of good feautre
